apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin       # required field for kubernetes.io/basic-auth
  password: t0p-Secret  # required field for kubernetes.io/basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-opaque
type: Opaque
stringData:
  secret1: test1       
  secret2: t0p-Secret 